SELECT *
FROM SALES

SELECT *
FROM PRODUCTS

SELECT*
FROM CUSTOMER

UPDATE CUSTOMER
SET Age=( SELECT (AVG(Age)) FROM CUSTOMER WHERE AGE IS NOT NULL) WHERE Age is null

SELECT Age 
FROM CUSTOMER

----TOP SELLING PRODUCT CATEGORY
SELECT p.Category,
     SUM(s.Quantity*s.Price)AS TOTAL_SALES
FROM SALES s
JOIN PRODUCTS p
ON s.Product_Id=p.Product_Id
GROUP BY p.Category
ORDER BY TOTAL_SALES DESC

--AGE DISTRIBUTION
SELECT Age,COUNT(*) AS TOTAL_COUNT
FROM CUSTOMER
GROUP BY Age
ORDER BY TOTAL_COUNT DESC

--INCOME DISTRIBUTION
SELECT Income,COUNT(*) AS TOTAL_COUNT
FROM CUSTOMER 
GROUP BY Income
ORDER BY TOTAL_COUNT

--PRODUCT PERFOMANCE
SELECT p.Product_Name,SUM(s.Quantity*s.Price) AS TOTAL_SALES
FROM PRODUCTS p
JOIN SALES s
ON p.Product_Id=s.Product_Id
GROUP BY p.Product_Name
ORDER BY TOTAL_SALES DESC