SELECT*
FROM ONLINE_SALES

--SALES BY REGION
SELECT Region,SUM(Total_Revenue) AS Total_Sales
FROM ONLINE_SALES
GROUP BY Region
ORDER BY Total_Sales DESC

--SALES BY PRODUCT CATEGORY
SELECT Product_Category,SUM(Total_Revenue) AS Total_Sales
FROM ONLINE_SALES
GROUP BY Product_Category
ORDER BY Total_Sales DESC

--TOP SELLING PRODUCTS
SELECT Product_Name,SUM(Units_Sold)AS Total_Units_Sold
FROM ONLINE_SALES
GROUP BY Product_Name
ORDER BY Total_Units_Sold DESC

--LEAST SOLD PRODUCT
SELECT Product_Name,MIN(Units_Sold) AS MIN_SOLD
FROM ONLINE_SALES
GROUP BY Product_Name
ORDER BY MIN_SOLD ASC

--AVERAGE PRODUCT SALES PER REGION
SELECT Product_Category,Region,AVG(Total_Revenue) AS AVG_SALES
FROM ONLINE_SALES
GROUP BY Product_Category,Region
ORDER BY AVG_SALES DESC

--TOP PERFORMING CUSTOMER
SELECT Transaction_ID,Product_Category,SUM(Total_Revenue)AS TOTAL_BOUGHT
FROM ONLINE_SALES
GROUP BY Transaction_id,Product_Category
ORDER BY TOTAL_BOUGHT DESC

--TOP PAYMENT METHOD USED
SELECT MAX(Payment_Method) AS MAX_PAYMENT_METHOD
FROM ONLINE_SALES

--SALES BY PAYMENT_METHOD
SELECT Payment_Method,SUM(Total_Revenue) AS TOTAL_SALES
FROM ONLINE_SALES
GROUP BY Payment_Method
ORDER BY TOTAL_SALES DESC

--CONTRIBUTION OF EACH PRODUCT TO THE TOTAL REVENUE
SELECT Product_Category,SUM(Total_Revenue)AS Total_Sales,SUM(Total_Revenue)*100/SUM(SUM(Total_Revenue))OVER() AS Percentage_Contribution
FROM ONLINE_SALES
GROUP BY Product_Category
ORDER BY Total_Sales DESC

--CUSTOMER BEHAVIOR INSIGHTS
SELECT Product_Category,AVG(Units_Sold) AS AVG_UNITS_SOLD
FROM ONLINE_SALES
GROUP BY Product_Category
ORDER BY AVG_UNITS_SOLD DESC
